### ISSUE TITLE
Insert inferred typesignature for function

### ISSUE THREAD

**Issue by kRITZCREEK** [kRITZCREEK/psc-ide#111]
I think we have two options here:

**Use the warning emitted by the compiler**

Pros:
- We get typesignatures for non-exported functions

Cons:
- Every editor has to implement the functionality itself or we need to run the compiler from psc-ide

The other option is to **use the inferred types from the externs files** which would only give us suggestions for exported identifiers, but lets us move all the functionality into psc-ide.

**Comment by nwolverson** [comment]
I think the compiler JSON output should be augmented for missing type decl and wildcard usage so that we could easily do a replace suggestion (need to find the right range to indicate), I think this may be more generally useful.

But I also think using the type from externs sounds like something that would be worth `psc-ide` doing. I have a hacked together version of https://github.com/paf31/purescript-psci that finds out type information by compiling and reading externs files, ouch...

**Comment by kRITZCREEK** [comment]
Actually... Isn't the `type` command already giving us what we need? For every other piece of information we'd need to run the compiler. @nwolverson, Feel free to reopen if I'm mistaken.

**Comment by nwolverson** [comment]
You're right, "type from externs" is exactly what you do already, not sure what I was thinking on the 2nd half of my comment.
