### ISSUE TITLE
Identifiers don't seem to be parsed correctly.

### ISSUE THREAD

**Issue by epost** [kRITZCREEK/psc-ide#38]
Lookee here, the XXX is considered to be part of the ident:

    erik@munin:~/my-psc-ide-project $ echo "typeLookupXXX id" | ./psc-ide
    Symbol 'XXX id' not found.

**Comment by kRITZCREEK** [comment]
This is because `spaces` consumes zero or more whitespaces. Instead of using `(many1 whitespace)` it would be cleaner to switch to using a Tokenparser and treating the commands as reserved keywords.

Since we're figuring out a new protocol anyway I don't think it's critical as the API is mainly consumed by editor plugins.

**Comment by kRITZCREEK** [comment]
with the new api this is obsolete
