### ISSUE TITLE
Provide "ping" command

### ISSUE THREAD

**Issue by dbushenko** [kRITZCREEK/psc-ide#53]
If the user has wrong configuration for the psc-ide or psc-ide-server executables, then the psc-ide-emacs plugin shows awfull error reports, totally unclear. I need a ping command to be sure that all the chain is configured, otherwise I can show normal error report that the paths to the executables are misconfigured.

Would be nice to have 2 separate ping commands: one for client, one for server.

The ping command might look like this:

Request
{"command":"ping-server"}
or
{"command":"ping-client"}

Response: 
"pong"

**Comment by kRITZCREEK** [comment]
I'm not quite sure what a ping command for the client would look like. The client basically just passes everything it gets to the server and vice versa. It doesn't look at the messages at all.

Did you try using the `cwd` or `list` commands to check for the server.
I can give a more descriptive error message from the client if the server isn't available.

**Comment by nwolverson** [comment]
I was considering using `cwd` for that purpose, because you want to know
  * Is there a server running
  * On the right port
  * In the right project directory

Would imagine you want to see different errors if you can't find/run the executable or if it is running in the wrong place.

(I added support to start the server process but there might already be one running on the desired port for the wrong project)

**Comment by dbushenko** [comment]
Yes, server-side ping as "cwd" command is OK.
